# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shaofeng/workspace2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shaofeng/workspace2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shaofeng/workspace2/CMakeFiles /home/shaofeng/workspace2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shaofeng/workspace2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tinyxml

# Build rule for target.
tinyxml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyxml
.PHONY : tinyxml

# fast build rule for target.
tinyxml/fast:
	$(MAKE) -f CMakeFiles/tinyxml.dir/build.make CMakeFiles/tinyxml.dir/build
.PHONY : tinyxml/fast

#=============================================================================
# Target rules for targets named test_tcp_client

# Build rule for target.
test_tcp_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tcp_client
.PHONY : test_tcp_client

# fast build rule for target.
test_tcp_client/fast:
	$(MAKE) -f CMakeFiles/test_tcp_client.dir/build.make CMakeFiles/test_tcp_client.dir/build
.PHONY : test_tcp_client/fast

#=============================================================================
# Target rules for targets named rocket

# Build rule for target.
rocket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rocket
.PHONY : rocket

# fast build rule for target.
rocket/fast:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/build
.PHONY : rocket/fast

#=============================================================================
# Target rules for targets named test_log

# Build rule for target.
test_log: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_log
.PHONY : test_log

# fast build rule for target.
test_log/fast:
	$(MAKE) -f CMakeFiles/test_log.dir/build.make CMakeFiles/test_log.dir/build
.PHONY : test_log/fast

#=============================================================================
# Target rules for targets named test_eventloop

# Build rule for target.
test_eventloop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_eventloop
.PHONY : test_eventloop

# fast build rule for target.
test_eventloop/fast:
	$(MAKE) -f CMakeFiles/test_eventloop.dir/build.make CMakeFiles/test_eventloop.dir/build
.PHONY : test_eventloop/fast

#=============================================================================
# Target rules for targets named test_tcp

# Build rule for target.
test_tcp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tcp
.PHONY : test_tcp

# fast build rule for target.
test_tcp/fast:
	$(MAKE) -f CMakeFiles/test_tcp.dir/build.make CMakeFiles/test_tcp.dir/build
.PHONY : test_tcp/fast

rocket/common/config.o: rocket/common/config.cc.o

.PHONY : rocket/common/config.o

# target to build an object file
rocket/common/config.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/common/config.cc.o
.PHONY : rocket/common/config.cc.o

rocket/common/config.i: rocket/common/config.cc.i

.PHONY : rocket/common/config.i

# target to preprocess a source file
rocket/common/config.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/common/config.cc.i
.PHONY : rocket/common/config.cc.i

rocket/common/config.s: rocket/common/config.cc.s

.PHONY : rocket/common/config.s

# target to generate assembly for a file
rocket/common/config.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/common/config.cc.s
.PHONY : rocket/common/config.cc.s

rocket/common/log.o: rocket/common/log.cc.o

.PHONY : rocket/common/log.o

# target to build an object file
rocket/common/log.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/common/log.cc.o
.PHONY : rocket/common/log.cc.o

rocket/common/log.i: rocket/common/log.cc.i

.PHONY : rocket/common/log.i

# target to preprocess a source file
rocket/common/log.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/common/log.cc.i
.PHONY : rocket/common/log.cc.i

rocket/common/log.s: rocket/common/log.cc.s

.PHONY : rocket/common/log.s

# target to generate assembly for a file
rocket/common/log.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/common/log.cc.s
.PHONY : rocket/common/log.cc.s

rocket/common/tinystr.o: rocket/common/tinystr.cpp.o

.PHONY : rocket/common/tinystr.o

# target to build an object file
rocket/common/tinystr.cpp.o:
	$(MAKE) -f CMakeFiles/tinyxml.dir/build.make CMakeFiles/tinyxml.dir/rocket/common/tinystr.cpp.o
.PHONY : rocket/common/tinystr.cpp.o

rocket/common/tinystr.i: rocket/common/tinystr.cpp.i

.PHONY : rocket/common/tinystr.i

# target to preprocess a source file
rocket/common/tinystr.cpp.i:
	$(MAKE) -f CMakeFiles/tinyxml.dir/build.make CMakeFiles/tinyxml.dir/rocket/common/tinystr.cpp.i
.PHONY : rocket/common/tinystr.cpp.i

rocket/common/tinystr.s: rocket/common/tinystr.cpp.s

.PHONY : rocket/common/tinystr.s

# target to generate assembly for a file
rocket/common/tinystr.cpp.s:
	$(MAKE) -f CMakeFiles/tinyxml.dir/build.make CMakeFiles/tinyxml.dir/rocket/common/tinystr.cpp.s
.PHONY : rocket/common/tinystr.cpp.s

rocket/common/tinyxml.o: rocket/common/tinyxml.cpp.o

.PHONY : rocket/common/tinyxml.o

# target to build an object file
rocket/common/tinyxml.cpp.o:
	$(MAKE) -f CMakeFiles/tinyxml.dir/build.make CMakeFiles/tinyxml.dir/rocket/common/tinyxml.cpp.o
.PHONY : rocket/common/tinyxml.cpp.o

rocket/common/tinyxml.i: rocket/common/tinyxml.cpp.i

.PHONY : rocket/common/tinyxml.i

# target to preprocess a source file
rocket/common/tinyxml.cpp.i:
	$(MAKE) -f CMakeFiles/tinyxml.dir/build.make CMakeFiles/tinyxml.dir/rocket/common/tinyxml.cpp.i
.PHONY : rocket/common/tinyxml.cpp.i

rocket/common/tinyxml.s: rocket/common/tinyxml.cpp.s

.PHONY : rocket/common/tinyxml.s

# target to generate assembly for a file
rocket/common/tinyxml.cpp.s:
	$(MAKE) -f CMakeFiles/tinyxml.dir/build.make CMakeFiles/tinyxml.dir/rocket/common/tinyxml.cpp.s
.PHONY : rocket/common/tinyxml.cpp.s

rocket/common/tinyxmlerror.o: rocket/common/tinyxmlerror.cpp.o

.PHONY : rocket/common/tinyxmlerror.o

# target to build an object file
rocket/common/tinyxmlerror.cpp.o:
	$(MAKE) -f CMakeFiles/tinyxml.dir/build.make CMakeFiles/tinyxml.dir/rocket/common/tinyxmlerror.cpp.o
.PHONY : rocket/common/tinyxmlerror.cpp.o

rocket/common/tinyxmlerror.i: rocket/common/tinyxmlerror.cpp.i

.PHONY : rocket/common/tinyxmlerror.i

# target to preprocess a source file
rocket/common/tinyxmlerror.cpp.i:
	$(MAKE) -f CMakeFiles/tinyxml.dir/build.make CMakeFiles/tinyxml.dir/rocket/common/tinyxmlerror.cpp.i
.PHONY : rocket/common/tinyxmlerror.cpp.i

rocket/common/tinyxmlerror.s: rocket/common/tinyxmlerror.cpp.s

.PHONY : rocket/common/tinyxmlerror.s

# target to generate assembly for a file
rocket/common/tinyxmlerror.cpp.s:
	$(MAKE) -f CMakeFiles/tinyxml.dir/build.make CMakeFiles/tinyxml.dir/rocket/common/tinyxmlerror.cpp.s
.PHONY : rocket/common/tinyxmlerror.cpp.s

rocket/common/tinyxmlparser.o: rocket/common/tinyxmlparser.cpp.o

.PHONY : rocket/common/tinyxmlparser.o

# target to build an object file
rocket/common/tinyxmlparser.cpp.o:
	$(MAKE) -f CMakeFiles/tinyxml.dir/build.make CMakeFiles/tinyxml.dir/rocket/common/tinyxmlparser.cpp.o
.PHONY : rocket/common/tinyxmlparser.cpp.o

rocket/common/tinyxmlparser.i: rocket/common/tinyxmlparser.cpp.i

.PHONY : rocket/common/tinyxmlparser.i

# target to preprocess a source file
rocket/common/tinyxmlparser.cpp.i:
	$(MAKE) -f CMakeFiles/tinyxml.dir/build.make CMakeFiles/tinyxml.dir/rocket/common/tinyxmlparser.cpp.i
.PHONY : rocket/common/tinyxmlparser.cpp.i

rocket/common/tinyxmlparser.s: rocket/common/tinyxmlparser.cpp.s

.PHONY : rocket/common/tinyxmlparser.s

# target to generate assembly for a file
rocket/common/tinyxmlparser.cpp.s:
	$(MAKE) -f CMakeFiles/tinyxml.dir/build.make CMakeFiles/tinyxml.dir/rocket/common/tinyxmlparser.cpp.s
.PHONY : rocket/common/tinyxmlparser.cpp.s

rocket/common/util.o: rocket/common/util.cc.o

.PHONY : rocket/common/util.o

# target to build an object file
rocket/common/util.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/common/util.cc.o
.PHONY : rocket/common/util.cc.o

rocket/common/util.i: rocket/common/util.cc.i

.PHONY : rocket/common/util.i

# target to preprocess a source file
rocket/common/util.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/common/util.cc.i
.PHONY : rocket/common/util.cc.i

rocket/common/util.s: rocket/common/util.cc.s

.PHONY : rocket/common/util.s

# target to generate assembly for a file
rocket/common/util.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/common/util.cc.s
.PHONY : rocket/common/util.cc.s

rocket/net/coder/tinypb_coder.o: rocket/net/coder/tinypb_coder.cc.o

.PHONY : rocket/net/coder/tinypb_coder.o

# target to build an object file
rocket/net/coder/tinypb_coder.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/coder/tinypb_coder.cc.o
.PHONY : rocket/net/coder/tinypb_coder.cc.o

rocket/net/coder/tinypb_coder.i: rocket/net/coder/tinypb_coder.cc.i

.PHONY : rocket/net/coder/tinypb_coder.i

# target to preprocess a source file
rocket/net/coder/tinypb_coder.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/coder/tinypb_coder.cc.i
.PHONY : rocket/net/coder/tinypb_coder.cc.i

rocket/net/coder/tinypb_coder.s: rocket/net/coder/tinypb_coder.cc.s

.PHONY : rocket/net/coder/tinypb_coder.s

# target to generate assembly for a file
rocket/net/coder/tinypb_coder.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/coder/tinypb_coder.cc.s
.PHONY : rocket/net/coder/tinypb_coder.cc.s

rocket/net/coder/tinypb_protocol.o: rocket/net/coder/tinypb_protocol.cc.o

.PHONY : rocket/net/coder/tinypb_protocol.o

# target to build an object file
rocket/net/coder/tinypb_protocol.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/coder/tinypb_protocol.cc.o
.PHONY : rocket/net/coder/tinypb_protocol.cc.o

rocket/net/coder/tinypb_protocol.i: rocket/net/coder/tinypb_protocol.cc.i

.PHONY : rocket/net/coder/tinypb_protocol.i

# target to preprocess a source file
rocket/net/coder/tinypb_protocol.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/coder/tinypb_protocol.cc.i
.PHONY : rocket/net/coder/tinypb_protocol.cc.i

rocket/net/coder/tinypb_protocol.s: rocket/net/coder/tinypb_protocol.cc.s

.PHONY : rocket/net/coder/tinypb_protocol.s

# target to generate assembly for a file
rocket/net/coder/tinypb_protocol.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/coder/tinypb_protocol.cc.s
.PHONY : rocket/net/coder/tinypb_protocol.cc.s

rocket/net/eventLoop.o: rocket/net/eventLoop.cc.o

.PHONY : rocket/net/eventLoop.o

# target to build an object file
rocket/net/eventLoop.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/eventLoop.cc.o
.PHONY : rocket/net/eventLoop.cc.o

rocket/net/eventLoop.i: rocket/net/eventLoop.cc.i

.PHONY : rocket/net/eventLoop.i

# target to preprocess a source file
rocket/net/eventLoop.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/eventLoop.cc.i
.PHONY : rocket/net/eventLoop.cc.i

rocket/net/eventLoop.s: rocket/net/eventLoop.cc.s

.PHONY : rocket/net/eventLoop.s

# target to generate assembly for a file
rocket/net/eventLoop.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/eventLoop.cc.s
.PHONY : rocket/net/eventLoop.cc.s

rocket/net/fd_event.o: rocket/net/fd_event.cc.o

.PHONY : rocket/net/fd_event.o

# target to build an object file
rocket/net/fd_event.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/fd_event.cc.o
.PHONY : rocket/net/fd_event.cc.o

rocket/net/fd_event.i: rocket/net/fd_event.cc.i

.PHONY : rocket/net/fd_event.i

# target to preprocess a source file
rocket/net/fd_event.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/fd_event.cc.i
.PHONY : rocket/net/fd_event.cc.i

rocket/net/fd_event.s: rocket/net/fd_event.cc.s

.PHONY : rocket/net/fd_event.s

# target to generate assembly for a file
rocket/net/fd_event.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/fd_event.cc.s
.PHONY : rocket/net/fd_event.cc.s

rocket/net/fd_event_group.o: rocket/net/fd_event_group.cc.o

.PHONY : rocket/net/fd_event_group.o

# target to build an object file
rocket/net/fd_event_group.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/fd_event_group.cc.o
.PHONY : rocket/net/fd_event_group.cc.o

rocket/net/fd_event_group.i: rocket/net/fd_event_group.cc.i

.PHONY : rocket/net/fd_event_group.i

# target to preprocess a source file
rocket/net/fd_event_group.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/fd_event_group.cc.i
.PHONY : rocket/net/fd_event_group.cc.i

rocket/net/fd_event_group.s: rocket/net/fd_event_group.cc.s

.PHONY : rocket/net/fd_event_group.s

# target to generate assembly for a file
rocket/net/fd_event_group.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/fd_event_group.cc.s
.PHONY : rocket/net/fd_event_group.cc.s

rocket/net/io_thread.o: rocket/net/io_thread.cc.o

.PHONY : rocket/net/io_thread.o

# target to build an object file
rocket/net/io_thread.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/io_thread.cc.o
.PHONY : rocket/net/io_thread.cc.o

rocket/net/io_thread.i: rocket/net/io_thread.cc.i

.PHONY : rocket/net/io_thread.i

# target to preprocess a source file
rocket/net/io_thread.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/io_thread.cc.i
.PHONY : rocket/net/io_thread.cc.i

rocket/net/io_thread.s: rocket/net/io_thread.cc.s

.PHONY : rocket/net/io_thread.s

# target to generate assembly for a file
rocket/net/io_thread.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/io_thread.cc.s
.PHONY : rocket/net/io_thread.cc.s

rocket/net/io_thread_group.o: rocket/net/io_thread_group.cc.o

.PHONY : rocket/net/io_thread_group.o

# target to build an object file
rocket/net/io_thread_group.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/io_thread_group.cc.o
.PHONY : rocket/net/io_thread_group.cc.o

rocket/net/io_thread_group.i: rocket/net/io_thread_group.cc.i

.PHONY : rocket/net/io_thread_group.i

# target to preprocess a source file
rocket/net/io_thread_group.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/io_thread_group.cc.i
.PHONY : rocket/net/io_thread_group.cc.i

rocket/net/io_thread_group.s: rocket/net/io_thread_group.cc.s

.PHONY : rocket/net/io_thread_group.s

# target to generate assembly for a file
rocket/net/io_thread_group.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/io_thread_group.cc.s
.PHONY : rocket/net/io_thread_group.cc.s

rocket/net/rpc/rpc_controller.o: rocket/net/rpc/rpc_controller.cc.o

.PHONY : rocket/net/rpc/rpc_controller.o

# target to build an object file
rocket/net/rpc/rpc_controller.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/rpc/rpc_controller.cc.o
.PHONY : rocket/net/rpc/rpc_controller.cc.o

rocket/net/rpc/rpc_controller.i: rocket/net/rpc/rpc_controller.cc.i

.PHONY : rocket/net/rpc/rpc_controller.i

# target to preprocess a source file
rocket/net/rpc/rpc_controller.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/rpc/rpc_controller.cc.i
.PHONY : rocket/net/rpc/rpc_controller.cc.i

rocket/net/rpc/rpc_controller.s: rocket/net/rpc/rpc_controller.cc.s

.PHONY : rocket/net/rpc/rpc_controller.s

# target to generate assembly for a file
rocket/net/rpc/rpc_controller.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/rpc/rpc_controller.cc.s
.PHONY : rocket/net/rpc/rpc_controller.cc.s

rocket/net/rpc/rpc_dispatcher.o: rocket/net/rpc/rpc_dispatcher.cc.o

.PHONY : rocket/net/rpc/rpc_dispatcher.o

# target to build an object file
rocket/net/rpc/rpc_dispatcher.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/rpc/rpc_dispatcher.cc.o
.PHONY : rocket/net/rpc/rpc_dispatcher.cc.o

rocket/net/rpc/rpc_dispatcher.i: rocket/net/rpc/rpc_dispatcher.cc.i

.PHONY : rocket/net/rpc/rpc_dispatcher.i

# target to preprocess a source file
rocket/net/rpc/rpc_dispatcher.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/rpc/rpc_dispatcher.cc.i
.PHONY : rocket/net/rpc/rpc_dispatcher.cc.i

rocket/net/rpc/rpc_dispatcher.s: rocket/net/rpc/rpc_dispatcher.cc.s

.PHONY : rocket/net/rpc/rpc_dispatcher.s

# target to generate assembly for a file
rocket/net/rpc/rpc_dispatcher.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/rpc/rpc_dispatcher.cc.s
.PHONY : rocket/net/rpc/rpc_dispatcher.cc.s

rocket/net/tcp/net_addr.o: rocket/net/tcp/net_addr.cc.o

.PHONY : rocket/net/tcp/net_addr.o

# target to build an object file
rocket/net/tcp/net_addr.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/net_addr.cc.o
.PHONY : rocket/net/tcp/net_addr.cc.o

rocket/net/tcp/net_addr.i: rocket/net/tcp/net_addr.cc.i

.PHONY : rocket/net/tcp/net_addr.i

# target to preprocess a source file
rocket/net/tcp/net_addr.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/net_addr.cc.i
.PHONY : rocket/net/tcp/net_addr.cc.i

rocket/net/tcp/net_addr.s: rocket/net/tcp/net_addr.cc.s

.PHONY : rocket/net/tcp/net_addr.s

# target to generate assembly for a file
rocket/net/tcp/net_addr.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/net_addr.cc.s
.PHONY : rocket/net/tcp/net_addr.cc.s

rocket/net/tcp/tcp_acceptor.o: rocket/net/tcp/tcp_acceptor.cc.o

.PHONY : rocket/net/tcp/tcp_acceptor.o

# target to build an object file
rocket/net/tcp/tcp_acceptor.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/tcp_acceptor.cc.o
.PHONY : rocket/net/tcp/tcp_acceptor.cc.o

rocket/net/tcp/tcp_acceptor.i: rocket/net/tcp/tcp_acceptor.cc.i

.PHONY : rocket/net/tcp/tcp_acceptor.i

# target to preprocess a source file
rocket/net/tcp/tcp_acceptor.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/tcp_acceptor.cc.i
.PHONY : rocket/net/tcp/tcp_acceptor.cc.i

rocket/net/tcp/tcp_acceptor.s: rocket/net/tcp/tcp_acceptor.cc.s

.PHONY : rocket/net/tcp/tcp_acceptor.s

# target to generate assembly for a file
rocket/net/tcp/tcp_acceptor.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/tcp_acceptor.cc.s
.PHONY : rocket/net/tcp/tcp_acceptor.cc.s

rocket/net/tcp/tcp_buffer.o: rocket/net/tcp/tcp_buffer.cc.o

.PHONY : rocket/net/tcp/tcp_buffer.o

# target to build an object file
rocket/net/tcp/tcp_buffer.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/tcp_buffer.cc.o
.PHONY : rocket/net/tcp/tcp_buffer.cc.o

rocket/net/tcp/tcp_buffer.i: rocket/net/tcp/tcp_buffer.cc.i

.PHONY : rocket/net/tcp/tcp_buffer.i

# target to preprocess a source file
rocket/net/tcp/tcp_buffer.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/tcp_buffer.cc.i
.PHONY : rocket/net/tcp/tcp_buffer.cc.i

rocket/net/tcp/tcp_buffer.s: rocket/net/tcp/tcp_buffer.cc.s

.PHONY : rocket/net/tcp/tcp_buffer.s

# target to generate assembly for a file
rocket/net/tcp/tcp_buffer.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/tcp_buffer.cc.s
.PHONY : rocket/net/tcp/tcp_buffer.cc.s

rocket/net/tcp/tcp_client.o: rocket/net/tcp/tcp_client.cc.o

.PHONY : rocket/net/tcp/tcp_client.o

# target to build an object file
rocket/net/tcp/tcp_client.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/tcp_client.cc.o
.PHONY : rocket/net/tcp/tcp_client.cc.o

rocket/net/tcp/tcp_client.i: rocket/net/tcp/tcp_client.cc.i

.PHONY : rocket/net/tcp/tcp_client.i

# target to preprocess a source file
rocket/net/tcp/tcp_client.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/tcp_client.cc.i
.PHONY : rocket/net/tcp/tcp_client.cc.i

rocket/net/tcp/tcp_client.s: rocket/net/tcp/tcp_client.cc.s

.PHONY : rocket/net/tcp/tcp_client.s

# target to generate assembly for a file
rocket/net/tcp/tcp_client.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/tcp_client.cc.s
.PHONY : rocket/net/tcp/tcp_client.cc.s

rocket/net/tcp/tcp_connection.o: rocket/net/tcp/tcp_connection.cc.o

.PHONY : rocket/net/tcp/tcp_connection.o

# target to build an object file
rocket/net/tcp/tcp_connection.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/tcp_connection.cc.o
.PHONY : rocket/net/tcp/tcp_connection.cc.o

rocket/net/tcp/tcp_connection.i: rocket/net/tcp/tcp_connection.cc.i

.PHONY : rocket/net/tcp/tcp_connection.i

# target to preprocess a source file
rocket/net/tcp/tcp_connection.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/tcp_connection.cc.i
.PHONY : rocket/net/tcp/tcp_connection.cc.i

rocket/net/tcp/tcp_connection.s: rocket/net/tcp/tcp_connection.cc.s

.PHONY : rocket/net/tcp/tcp_connection.s

# target to generate assembly for a file
rocket/net/tcp/tcp_connection.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/tcp_connection.cc.s
.PHONY : rocket/net/tcp/tcp_connection.cc.s

rocket/net/tcp/tcp_server.o: rocket/net/tcp/tcp_server.cc.o

.PHONY : rocket/net/tcp/tcp_server.o

# target to build an object file
rocket/net/tcp/tcp_server.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/tcp_server.cc.o
.PHONY : rocket/net/tcp/tcp_server.cc.o

rocket/net/tcp/tcp_server.i: rocket/net/tcp/tcp_server.cc.i

.PHONY : rocket/net/tcp/tcp_server.i

# target to preprocess a source file
rocket/net/tcp/tcp_server.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/tcp_server.cc.i
.PHONY : rocket/net/tcp/tcp_server.cc.i

rocket/net/tcp/tcp_server.s: rocket/net/tcp/tcp_server.cc.s

.PHONY : rocket/net/tcp/tcp_server.s

# target to generate assembly for a file
rocket/net/tcp/tcp_server.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/tcp/tcp_server.cc.s
.PHONY : rocket/net/tcp/tcp_server.cc.s

rocket/net/timer.o: rocket/net/timer.cc.o

.PHONY : rocket/net/timer.o

# target to build an object file
rocket/net/timer.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/timer.cc.o
.PHONY : rocket/net/timer.cc.o

rocket/net/timer.i: rocket/net/timer.cc.i

.PHONY : rocket/net/timer.i

# target to preprocess a source file
rocket/net/timer.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/timer.cc.i
.PHONY : rocket/net/timer.cc.i

rocket/net/timer.s: rocket/net/timer.cc.s

.PHONY : rocket/net/timer.s

# target to generate assembly for a file
rocket/net/timer.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/timer.cc.s
.PHONY : rocket/net/timer.cc.s

rocket/net/timer_event.o: rocket/net/timer_event.cc.o

.PHONY : rocket/net/timer_event.o

# target to build an object file
rocket/net/timer_event.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/timer_event.cc.o
.PHONY : rocket/net/timer_event.cc.o

rocket/net/timer_event.i: rocket/net/timer_event.cc.i

.PHONY : rocket/net/timer_event.i

# target to preprocess a source file
rocket/net/timer_event.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/timer_event.cc.i
.PHONY : rocket/net/timer_event.cc.i

rocket/net/timer_event.s: rocket/net/timer_event.cc.s

.PHONY : rocket/net/timer_event.s

# target to generate assembly for a file
rocket/net/timer_event.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/timer_event.cc.s
.PHONY : rocket/net/timer_event.cc.s

rocket/net/wakeup_fd.o: rocket/net/wakeup_fd.cc.o

.PHONY : rocket/net/wakeup_fd.o

# target to build an object file
rocket/net/wakeup_fd.cc.o:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/wakeup_fd.cc.o
.PHONY : rocket/net/wakeup_fd.cc.o

rocket/net/wakeup_fd.i: rocket/net/wakeup_fd.cc.i

.PHONY : rocket/net/wakeup_fd.i

# target to preprocess a source file
rocket/net/wakeup_fd.cc.i:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/wakeup_fd.cc.i
.PHONY : rocket/net/wakeup_fd.cc.i

rocket/net/wakeup_fd.s: rocket/net/wakeup_fd.cc.s

.PHONY : rocket/net/wakeup_fd.s

# target to generate assembly for a file
rocket/net/wakeup_fd.cc.s:
	$(MAKE) -f CMakeFiles/rocket.dir/build.make CMakeFiles/rocket.dir/rocket/net/wakeup_fd.cc.s
.PHONY : rocket/net/wakeup_fd.cc.s

tests/test_eventloop.o: tests/test_eventloop.cc.o

.PHONY : tests/test_eventloop.o

# target to build an object file
tests/test_eventloop.cc.o:
	$(MAKE) -f CMakeFiles/test_eventloop.dir/build.make CMakeFiles/test_eventloop.dir/tests/test_eventloop.cc.o
.PHONY : tests/test_eventloop.cc.o

tests/test_eventloop.i: tests/test_eventloop.cc.i

.PHONY : tests/test_eventloop.i

# target to preprocess a source file
tests/test_eventloop.cc.i:
	$(MAKE) -f CMakeFiles/test_eventloop.dir/build.make CMakeFiles/test_eventloop.dir/tests/test_eventloop.cc.i
.PHONY : tests/test_eventloop.cc.i

tests/test_eventloop.s: tests/test_eventloop.cc.s

.PHONY : tests/test_eventloop.s

# target to generate assembly for a file
tests/test_eventloop.cc.s:
	$(MAKE) -f CMakeFiles/test_eventloop.dir/build.make CMakeFiles/test_eventloop.dir/tests/test_eventloop.cc.s
.PHONY : tests/test_eventloop.cc.s

tests/test_log.o: tests/test_log.cc.o

.PHONY : tests/test_log.o

# target to build an object file
tests/test_log.cc.o:
	$(MAKE) -f CMakeFiles/test_log.dir/build.make CMakeFiles/test_log.dir/tests/test_log.cc.o
.PHONY : tests/test_log.cc.o

tests/test_log.i: tests/test_log.cc.i

.PHONY : tests/test_log.i

# target to preprocess a source file
tests/test_log.cc.i:
	$(MAKE) -f CMakeFiles/test_log.dir/build.make CMakeFiles/test_log.dir/tests/test_log.cc.i
.PHONY : tests/test_log.cc.i

tests/test_log.s: tests/test_log.cc.s

.PHONY : tests/test_log.s

# target to generate assembly for a file
tests/test_log.cc.s:
	$(MAKE) -f CMakeFiles/test_log.dir/build.make CMakeFiles/test_log.dir/tests/test_log.cc.s
.PHONY : tests/test_log.cc.s

tests/test_tcp.o: tests/test_tcp.cc.o

.PHONY : tests/test_tcp.o

# target to build an object file
tests/test_tcp.cc.o:
	$(MAKE) -f CMakeFiles/test_tcp.dir/build.make CMakeFiles/test_tcp.dir/tests/test_tcp.cc.o
.PHONY : tests/test_tcp.cc.o

tests/test_tcp.i: tests/test_tcp.cc.i

.PHONY : tests/test_tcp.i

# target to preprocess a source file
tests/test_tcp.cc.i:
	$(MAKE) -f CMakeFiles/test_tcp.dir/build.make CMakeFiles/test_tcp.dir/tests/test_tcp.cc.i
.PHONY : tests/test_tcp.cc.i

tests/test_tcp.s: tests/test_tcp.cc.s

.PHONY : tests/test_tcp.s

# target to generate assembly for a file
tests/test_tcp.cc.s:
	$(MAKE) -f CMakeFiles/test_tcp.dir/build.make CMakeFiles/test_tcp.dir/tests/test_tcp.cc.s
.PHONY : tests/test_tcp.cc.s

tests/test_tcp_client.o: tests/test_tcp_client.cc.o

.PHONY : tests/test_tcp_client.o

# target to build an object file
tests/test_tcp_client.cc.o:
	$(MAKE) -f CMakeFiles/test_tcp_client.dir/build.make CMakeFiles/test_tcp_client.dir/tests/test_tcp_client.cc.o
.PHONY : tests/test_tcp_client.cc.o

tests/test_tcp_client.i: tests/test_tcp_client.cc.i

.PHONY : tests/test_tcp_client.i

# target to preprocess a source file
tests/test_tcp_client.cc.i:
	$(MAKE) -f CMakeFiles/test_tcp_client.dir/build.make CMakeFiles/test_tcp_client.dir/tests/test_tcp_client.cc.i
.PHONY : tests/test_tcp_client.cc.i

tests/test_tcp_client.s: tests/test_tcp_client.cc.s

.PHONY : tests/test_tcp_client.s

# target to generate assembly for a file
tests/test_tcp_client.cc.s:
	$(MAKE) -f CMakeFiles/test_tcp_client.dir/build.make CMakeFiles/test_tcp_client.dir/tests/test_tcp_client.cc.s
.PHONY : tests/test_tcp_client.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... tinyxml"
	@echo "... test_tcp_client"
	@echo "... rocket"
	@echo "... edit_cache"
	@echo "... test_log"
	@echo "... test_eventloop"
	@echo "... rebuild_cache"
	@echo "... test_tcp"
	@echo "... rocket/common/config.o"
	@echo "... rocket/common/config.i"
	@echo "... rocket/common/config.s"
	@echo "... rocket/common/log.o"
	@echo "... rocket/common/log.i"
	@echo "... rocket/common/log.s"
	@echo "... rocket/common/tinystr.o"
	@echo "... rocket/common/tinystr.i"
	@echo "... rocket/common/tinystr.s"
	@echo "... rocket/common/tinyxml.o"
	@echo "... rocket/common/tinyxml.i"
	@echo "... rocket/common/tinyxml.s"
	@echo "... rocket/common/tinyxmlerror.o"
	@echo "... rocket/common/tinyxmlerror.i"
	@echo "... rocket/common/tinyxmlerror.s"
	@echo "... rocket/common/tinyxmlparser.o"
	@echo "... rocket/common/tinyxmlparser.i"
	@echo "... rocket/common/tinyxmlparser.s"
	@echo "... rocket/common/util.o"
	@echo "... rocket/common/util.i"
	@echo "... rocket/common/util.s"
	@echo "... rocket/net/coder/tinypb_coder.o"
	@echo "... rocket/net/coder/tinypb_coder.i"
	@echo "... rocket/net/coder/tinypb_coder.s"
	@echo "... rocket/net/coder/tinypb_protocol.o"
	@echo "... rocket/net/coder/tinypb_protocol.i"
	@echo "... rocket/net/coder/tinypb_protocol.s"
	@echo "... rocket/net/eventLoop.o"
	@echo "... rocket/net/eventLoop.i"
	@echo "... rocket/net/eventLoop.s"
	@echo "... rocket/net/fd_event.o"
	@echo "... rocket/net/fd_event.i"
	@echo "... rocket/net/fd_event.s"
	@echo "... rocket/net/fd_event_group.o"
	@echo "... rocket/net/fd_event_group.i"
	@echo "... rocket/net/fd_event_group.s"
	@echo "... rocket/net/io_thread.o"
	@echo "... rocket/net/io_thread.i"
	@echo "... rocket/net/io_thread.s"
	@echo "... rocket/net/io_thread_group.o"
	@echo "... rocket/net/io_thread_group.i"
	@echo "... rocket/net/io_thread_group.s"
	@echo "... rocket/net/rpc/rpc_controller.o"
	@echo "... rocket/net/rpc/rpc_controller.i"
	@echo "... rocket/net/rpc/rpc_controller.s"
	@echo "... rocket/net/rpc/rpc_dispatcher.o"
	@echo "... rocket/net/rpc/rpc_dispatcher.i"
	@echo "... rocket/net/rpc/rpc_dispatcher.s"
	@echo "... rocket/net/tcp/net_addr.o"
	@echo "... rocket/net/tcp/net_addr.i"
	@echo "... rocket/net/tcp/net_addr.s"
	@echo "... rocket/net/tcp/tcp_acceptor.o"
	@echo "... rocket/net/tcp/tcp_acceptor.i"
	@echo "... rocket/net/tcp/tcp_acceptor.s"
	@echo "... rocket/net/tcp/tcp_buffer.o"
	@echo "... rocket/net/tcp/tcp_buffer.i"
	@echo "... rocket/net/tcp/tcp_buffer.s"
	@echo "... rocket/net/tcp/tcp_client.o"
	@echo "... rocket/net/tcp/tcp_client.i"
	@echo "... rocket/net/tcp/tcp_client.s"
	@echo "... rocket/net/tcp/tcp_connection.o"
	@echo "... rocket/net/tcp/tcp_connection.i"
	@echo "... rocket/net/tcp/tcp_connection.s"
	@echo "... rocket/net/tcp/tcp_server.o"
	@echo "... rocket/net/tcp/tcp_server.i"
	@echo "... rocket/net/tcp/tcp_server.s"
	@echo "... rocket/net/timer.o"
	@echo "... rocket/net/timer.i"
	@echo "... rocket/net/timer.s"
	@echo "... rocket/net/timer_event.o"
	@echo "... rocket/net/timer_event.i"
	@echo "... rocket/net/timer_event.s"
	@echo "... rocket/net/wakeup_fd.o"
	@echo "... rocket/net/wakeup_fd.i"
	@echo "... rocket/net/wakeup_fd.s"
	@echo "... tests/test_eventloop.o"
	@echo "... tests/test_eventloop.i"
	@echo "... tests/test_eventloop.s"
	@echo "... tests/test_log.o"
	@echo "... tests/test_log.i"
	@echo "... tests/test_log.s"
	@echo "... tests/test_tcp.o"
	@echo "... tests/test_tcp.i"
	@echo "... tests/test_tcp.s"
	@echo "... tests/test_tcp_client.o"
	@echo "... tests/test_tcp_client.i"
	@echo "... tests/test_tcp_client.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

